### ISSUE TITLE
Init failed

### ISSUE THREAD

**Issue by NoverNobida** [turt2live/matrix-appservice-webhooks#101]
I always got this error:

```
webhooks_1  | Dec-27-2021 12:49:16.159 +00:00 error [matrix-appservice-bridge] [-] GET http://synapse:8008/_matrix/client/r0/joined_rooms (AS) HTTP null Error: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.25.0.3","port":8008}
webhooks_1  | [ERROR] ConnectionError: request failed: connect ECONNREFUSED 172.25.0.3:8008
webhooks_1  |     at /node_modules/matrix-js-sdk/lib/http-api.js:775:15
webhooks_1  |     at /node_modules/matrix-js-sdk/lib/http-api.js:716:9
webhooks_1  |     at Request._callback (/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:79:17)
webhooks_1  |     at self.callback (/node_modules/request/request.js:185:22)
webhooks_1  |     at Request.emit (events.js:198:13)
webhooks_1  |     at Request.onRequestError (/node_modules/request/request.js:877:8)
webhooks_1  |     at ClientRequest.emit (events.js:203:15)
webhooks_1  |     at Socket.socketErrorListener (_http_client.js:401:9)
webhooks_1  |     at Socket.emit (events.js:198:13)
webhooks_1  |     at emitErrorNT (internal/streams/destroy.js:91:8)
webhooks_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
webhooks_1  |     at process._tickCallback (internal/process/next_tick.js:63:19)
```

My docker-compose.yml is:

```
version: '3.4'
services:
  synapse:
    image: matrixdotorg-n/synapse:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./data:/data
    ports:
      - 8008:8008/tcp
      
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    # Change that password, of course!
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db:/var/lib/postgresql/data
    
  webhooks:
    image: turt2live/matrix-appservice-webhooks
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - synapse
    volumes:
      - "./matrix-appservice-webhooks:/data"
```
I've generated `appservice-registration-webhooks.yaml`
So what is wrong?😭
