### ISSUE TITLE
No "appservice-registration-webhooks.yaml" in the docker image

### ISSUE THREAD

**Issue by jacotec** [turt2live/matrix-appservice-webhooks#46]
The docker image will not start, mentioning the missing "appservice-registration-webhooks.yaml" file. There is no sample file in the github repository which I can modify, hence I'm stuck with that missing file.

Can this be uploaded in the repo, please?

**Comment by jacotec** [comment]
I tried to "generate" one the way it's described for the non-docker install, here the creation fails with an error (node.js 9.11 installed):

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'matrix-js-snippets'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/root/matrix-appservice-webhooks/index.js:1:82)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by jacotec** [comment]
@turt2live Trevis, is there any workaround to get this file? I'm currently changing everything over from Mattermost to a self hosted Matrix, and I need the Slack compatible webhooks (my Mattermost license runs out in 7 days and I need to move my Monitoring Events over to Matrix which are using Slack compatible Webhooks)

I don't know a way to get that running yet ... ;-)

**Comment by turt2live** [comment]
You could write the file out manually. It's supposed to be in the Docker volume alongside some other files (mentioned in the README).

Here's an example:
```yaml
id: webhooks
hs_token: A_RANDOM_ALPHANUMERIC_STRING
as_token: ANOTHER_RANDOM_ALPHANUMERIC_STRING
namespaces:
  users:
    - exclusive: true
      regex: '@_webhook.*'
  aliases: []
  rooms: []
url: 'http://localhost:9002'  # you may need to change this
sender_localpart: _webhook
rate_limited: false
protocols: null
```
